// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: MyDemo.proto

/*
	Package usercmd is a generated protocol buffer package.

	It is generated from these files:
		MyDemo.proto

	It has these top-level messages:
		MoveC2SMsg
		MoveS2CMsg
		LoginC2SMsg
		LoginS2CMsg
		SearchC2SMsg
		SearchS2CMsg
		GameStartS2CMsg
		ChangeColorS2CMsg
		GameEndS2CMsg
		GameEnergyS2CMsg
		SynTimeS2CMsg
		CreateItemsS2CMsg
		DestroyItemsS2CMsg
*/
package usercmd

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DemoTypeCmd int32

const (
	DemoTypeCmd_MoveReq        DemoTypeCmd = 1
	DemoTypeCmd_MoveRes        DemoTypeCmd = 2
	DemoTypeCmd_LoginReq       DemoTypeCmd = 3
	DemoTypeCmd_LoginRes       DemoTypeCmd = 4
	DemoTypeCmd_SearchReq      DemoTypeCmd = 5
	DemoTypeCmd_SearchRes      DemoTypeCmd = 6
	DemoTypeCmd_GameStart      DemoTypeCmd = 7
	DemoTypeCmd_ChangeColorRes DemoTypeCmd = 9
	DemoTypeCmd_GameEnd        DemoTypeCmd = 10
	DemoTypeCmd_GameEnergy     DemoTypeCmd = 11
	DemoTypeCmd_GameTime       DemoTypeCmd = 12
	DemoTypeCmd_ItemCreate     DemoTypeCmd = 13
	DemoTypeCmd_ItemDestroy    DemoTypeCmd = 14
)

var DemoTypeCmd_name = map[int32]string{
	1:  "MoveReq",
	2:  "MoveRes",
	3:  "LoginReq",
	4:  "LoginRes",
	5:  "SearchReq",
	6:  "SearchRes",
	7:  "GameStart",
	9:  "ChangeColorRes",
	10: "GameEnd",
	11: "GameEnergy",
	12: "GameTime",
	13: "ItemCreate",
	14: "ItemDestroy",
}
var DemoTypeCmd_value = map[string]int32{
	"MoveReq":        1,
	"MoveRes":        2,
	"LoginReq":       3,
	"LoginRes":       4,
	"SearchReq":      5,
	"SearchRes":      6,
	"GameStart":      7,
	"ChangeColorRes": 9,
	"GameEnd":        10,
	"GameEnergy":     11,
	"GameTime":       12,
	"ItemCreate":     13,
	"ItemDestroy":    14,
}

func (x DemoTypeCmd) Enum() *DemoTypeCmd {
	p := new(DemoTypeCmd)
	*p = x
	return p
}
func (x DemoTypeCmd) String() string {
	return proto.EnumName(DemoTypeCmd_name, int32(x))
}
func (x *DemoTypeCmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DemoTypeCmd_value, data, "DemoTypeCmd")
	if err != nil {
		return err
	}
	*x = DemoTypeCmd(value)
	return nil
}
func (DemoTypeCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{0} }

type ColorType int32

const (
	ColorType_origin ColorType = 0
	ColorType_red    ColorType = 1
	ColorType_yellow ColorType = 2
	ColorType_blue   ColorType = 3
)

var ColorType_name = map[int32]string{
	0: "origin",
	1: "red",
	2: "yellow",
	3: "blue",
}
var ColorType_value = map[string]int32{
	"origin": 0,
	"red":    1,
	"yellow": 2,
	"blue":   3,
}

func (x ColorType) Enum() *ColorType {
	p := new(ColorType)
	*p = x
	return p
}
func (x ColorType) String() string {
	return proto.EnumName(ColorType_name, int32(x))
}
func (x *ColorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ColorType_value, data, "ColorType")
	if err != nil {
		return err
	}
	*x = ColorType(value)
	return nil
}
func (ColorType) EnumDescriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{1} }

type ItemType int32

const (
	ItemType_unknown ItemType = 0
	ItemType_virus   ItemType = 1
	ItemType_dyeing  ItemType = 2
)

var ItemType_name = map[int32]string{
	0: "unknown",
	1: "virus",
	2: "dyeing",
}
var ItemType_value = map[string]int32{
	"unknown": 0,
	"virus":   1,
	"dyeing":  2,
}

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}
func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}
func (x *ItemType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ItemType_value, data, "ItemType")
	if err != nil {
		return err
	}
	*x = ItemType(value)
	return nil
}
func (ItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{2} }

// 客户端发送当前位置
type MoveC2SMsg struct {
	PlayerId uint32  `protobuf:"varint,1,req,name=playerId" json:"playerId"`
	PosX     float32 `protobuf:"fixed32,2,req,name=posX" json:"posX"`
	PosY     float32 `protobuf:"fixed32,3,req,name=posY" json:"posY"`
	PosZ     float32 `protobuf:"fixed32,4,req,name=posZ" json:"posZ"`
}

func (m *MoveC2SMsg) Reset()                    { *m = MoveC2SMsg{} }
func (m *MoveC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*MoveC2SMsg) ProtoMessage()               {}
func (*MoveC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{0} }

func (m *MoveC2SMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MoveC2SMsg) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *MoveC2SMsg) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *MoveC2SMsg) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

// 服务器广播房间内该玩家位置
type MoveS2CMsg struct {
	PlayerId uint32  `protobuf:"varint,1,req,name=playerId" json:"playerId"`
	PosX     float32 `protobuf:"fixed32,2,req,name=posX" json:"posX"`
	PosY     float32 `protobuf:"fixed32,3,req,name=posY" json:"posY"`
	PosZ     float32 `protobuf:"fixed32,4,req,name=posZ" json:"posZ"`
}

func (m *MoveS2CMsg) Reset()                    { *m = MoveS2CMsg{} }
func (m *MoveS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*MoveS2CMsg) ProtoMessage()               {}
func (*MoveS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{1} }

func (m *MoveS2CMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MoveS2CMsg) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *MoveS2CMsg) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *MoveS2CMsg) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

// 客户端发送登录请求  name = 玩家 + random(1~999)
// 比如叫玩家233或者玩家012
type LoginC2SMsg struct {
	Name string `protobuf:"bytes,1,req,name=name" json:"name"`
}

func (m *LoginC2SMsg) Reset()                    { *m = LoginC2SMsg{} }
func (m *LoginC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginC2SMsg) ProtoMessage()               {}
func (*LoginC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{2} }

func (m *LoginC2SMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 服务器判断回传登陆响应
// 玩家的个人id
type LoginS2CMsg struct {
	PlayerId uint32 `protobuf:"varint,1,req,name=playerId" json:"playerId"`
}

func (m *LoginS2CMsg) Reset()                    { *m = LoginS2CMsg{} }
func (m *LoginS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginS2CMsg) ProtoMessage()               {}
func (*LoginS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{3} }

func (m *LoginS2CMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 客户端请求游戏匹配
type SearchC2SMsg struct {
	PlayerId uint32 `protobuf:"varint,1,req,name=playerId" json:"playerId"`
}

func (m *SearchC2SMsg) Reset()                    { *m = SearchC2SMsg{} }
func (m *SearchC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*SearchC2SMsg) ProtoMessage()               {}
func (*SearchC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{4} }

func (m *SearchC2SMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 服务器通知匹配信息
type SearchS2CMsg struct {
	RoomId uint32                `protobuf:"varint,1,req,name=roomId" json:"roomId"`
	Nums   []*SearchS2CMsgPlayer `protobuf:"bytes,2,rep,name=nums" json:"nums,omitempty"`
}

func (m *SearchS2CMsg) Reset()                    { *m = SearchS2CMsg{} }
func (m *SearchS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*SearchS2CMsg) ProtoMessage()               {}
func (*SearchS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{5} }

func (m *SearchS2CMsg) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *SearchS2CMsg) GetNums() []*SearchS2CMsgPlayer {
	if m != nil {
		return m.Nums
	}
	return nil
}

type SearchS2CMsgPlayer struct {
	PlayerId uint32 `protobuf:"varint,1,req,name=playerId" json:"playerId"`
	Name     string `protobuf:"bytes,2,req,name=name" json:"name"`
}

func (m *SearchS2CMsgPlayer) Reset()                    { *m = SearchS2CMsgPlayer{} }
func (m *SearchS2CMsgPlayer) String() string            { return proto.CompactTextString(m) }
func (*SearchS2CMsgPlayer) ProtoMessage()               {}
func (*SearchS2CMsgPlayer) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{5, 0} }

func (m *SearchS2CMsgPlayer) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *SearchS2CMsgPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 服务器主动推送
// 游戏开始消息用于初始化信息  目前 是推送每个玩家角色的出生位置
type GameStartS2CMsg struct {
	Nums    []*GameStartS2CMsgPosition `protobuf:"bytes,1,rep,name=nums" json:"nums,omitempty"`
	Edgenum uint32                     `protobuf:"varint,2,req,name=edgenum" json:"edgenum"`
}

func (m *GameStartS2CMsg) Reset()                    { *m = GameStartS2CMsg{} }
func (m *GameStartS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*GameStartS2CMsg) ProtoMessage()               {}
func (*GameStartS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{6} }

func (m *GameStartS2CMsg) GetNums() []*GameStartS2CMsgPosition {
	if m != nil {
		return m.Nums
	}
	return nil
}

func (m *GameStartS2CMsg) GetEdgenum() uint32 {
	if m != nil {
		return m.Edgenum
	}
	return 0
}

type GameStartS2CMsgPosition struct {
	PlayerId uint32    `protobuf:"varint,1,req,name=playerId" json:"playerId"`
	Row      uint32    `protobuf:"varint,2,req,name=row" json:"row"`
	Col      uint32    `protobuf:"varint,3,req,name=col" json:"col"`
	Color    ColorType `protobuf:"varint,4,req,name=color,enum=usercmd.ColorType" json:"color"`
}

func (m *GameStartS2CMsgPosition) Reset()                    { *m = GameStartS2CMsgPosition{} }
func (m *GameStartS2CMsgPosition) String() string            { return proto.CompactTextString(m) }
func (*GameStartS2CMsgPosition) ProtoMessage()               {}
func (*GameStartS2CMsgPosition) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{6, 0} }

func (m *GameStartS2CMsgPosition) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GameStartS2CMsgPosition) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *GameStartS2CMsgPosition) GetCol() uint32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *GameStartS2CMsgPosition) GetColor() ColorType {
	if m != nil {
		return m.Color
	}
	return ColorType_origin
}

// 服务器广播  变色方块位置
type ChangeColorS2CMsg struct {
	Color ColorType `protobuf:"varint,1,req,name=color,enum=usercmd.ColorType" json:"color"`
	Row   uint32    `protobuf:"varint,2,req,name=row" json:"row"`
	Col   uint32    `protobuf:"varint,3,req,name=col" json:"col"`
}

func (m *ChangeColorS2CMsg) Reset()                    { *m = ChangeColorS2CMsg{} }
func (m *ChangeColorS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*ChangeColorS2CMsg) ProtoMessage()               {}
func (*ChangeColorS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{7} }

func (m *ChangeColorS2CMsg) GetColor() ColorType {
	if m != nil {
		return m.Color
	}
	return ColorType_origin
}

func (m *ChangeColorS2CMsg) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *ChangeColorS2CMsg) GetCol() uint32 {
	if m != nil {
		return m.Col
	}
	return 0
}

// 服务器主动推送
// 游戏倒计时1分钟后结束主动发送的消息
type GameEndS2CMsg struct {
	Color ColorType `protobuf:"varint,1,req,name=color,enum=usercmd.ColorType" json:"color"`
	Num   uint32    `protobuf:"varint,2,req,name=num" json:"num"`
}

func (m *GameEndS2CMsg) Reset()                    { *m = GameEndS2CMsg{} }
func (m *GameEndS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*GameEndS2CMsg) ProtoMessage()               {}
func (*GameEndS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{8} }

func (m *GameEndS2CMsg) GetColor() ColorType {
	if m != nil {
		return m.Color
	}
	return ColorType_origin
}

func (m *GameEndS2CMsg) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// 服务器主动推送
// 能量条信息
type GameEnergyS2CMsg struct {
	Color  ColorType `protobuf:"varint,1,req,name=color,enum=usercmd.ColorType" json:"color"`
	Status uint32    `protobuf:"varint,2,req,name=status" json:"status"`
}

func (m *GameEnergyS2CMsg) Reset()                    { *m = GameEnergyS2CMsg{} }
func (m *GameEnergyS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*GameEnergyS2CMsg) ProtoMessage()               {}
func (*GameEnergyS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{9} }

func (m *GameEnergyS2CMsg) GetColor() ColorType {
	if m != nil {
		return m.Color
	}
	return ColorType_origin
}

func (m *GameEnergyS2CMsg) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// 服务器主动推送
// 时间同步
type SynTimeS2CMsg struct {
	Tloop uint32 `protobuf:"varint,1,req,name=tloop" json:"tloop"`
}

func (m *SynTimeS2CMsg) Reset()                    { *m = SynTimeS2CMsg{} }
func (m *SynTimeS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*SynTimeS2CMsg) ProtoMessage()               {}
func (*SynTimeS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{10} }

func (m *SynTimeS2CMsg) GetTloop() uint32 {
	if m != nil {
		return m.Tloop
	}
	return 0
}

// 服务器主动推送
// 道具随机生成
type CreateItemsS2CMsg struct {
	Row  uint32   `protobuf:"varint,1,req,name=row" json:"row"`
	Col  uint32   `protobuf:"varint,2,req,name=col" json:"col"`
	Item ItemType `protobuf:"varint,3,req,name=item,enum=usercmd.ItemType" json:"item"`
}

func (m *CreateItemsS2CMsg) Reset()                    { *m = CreateItemsS2CMsg{} }
func (m *CreateItemsS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*CreateItemsS2CMsg) ProtoMessage()               {}
func (*CreateItemsS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{11} }

func (m *CreateItemsS2CMsg) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *CreateItemsS2CMsg) GetCol() uint32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *CreateItemsS2CMsg) GetItem() ItemType {
	if m != nil {
		return m.Item
	}
	return ItemType_unknown
}

// 服务器主动推送
// 道具销毁  可能是玩家吃了这个道具  也可能是到了刷新时间，道具被刷新
type DestroyItemsS2CMsg struct {
	Row uint32 `protobuf:"varint,1,req,name=row" json:"row"`
	Col uint32 `protobuf:"varint,2,req,name=col" json:"col"`
}

func (m *DestroyItemsS2CMsg) Reset()                    { *m = DestroyItemsS2CMsg{} }
func (m *DestroyItemsS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*DestroyItemsS2CMsg) ProtoMessage()               {}
func (*DestroyItemsS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptorMyDemo, []int{12} }

func (m *DestroyItemsS2CMsg) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *DestroyItemsS2CMsg) GetCol() uint32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func init() {
	proto.RegisterType((*MoveC2SMsg)(nil), "usercmd.MoveC2SMsg")
	proto.RegisterType((*MoveS2CMsg)(nil), "usercmd.MoveS2CMsg")
	proto.RegisterType((*LoginC2SMsg)(nil), "usercmd.LoginC2SMsg")
	proto.RegisterType((*LoginS2CMsg)(nil), "usercmd.LoginS2CMsg")
	proto.RegisterType((*SearchC2SMsg)(nil), "usercmd.SearchC2SMsg")
	proto.RegisterType((*SearchS2CMsg)(nil), "usercmd.SearchS2CMsg")
	proto.RegisterType((*SearchS2CMsgPlayer)(nil), "usercmd.SearchS2CMsg.player")
	proto.RegisterType((*GameStartS2CMsg)(nil), "usercmd.GameStartS2CMsg")
	proto.RegisterType((*GameStartS2CMsgPosition)(nil), "usercmd.GameStartS2CMsg.position")
	proto.RegisterType((*ChangeColorS2CMsg)(nil), "usercmd.ChangeColorS2CMsg")
	proto.RegisterType((*GameEndS2CMsg)(nil), "usercmd.GameEndS2CMsg")
	proto.RegisterType((*GameEnergyS2CMsg)(nil), "usercmd.GameEnergyS2CMsg")
	proto.RegisterType((*SynTimeS2CMsg)(nil), "usercmd.SynTimeS2CMsg")
	proto.RegisterType((*CreateItemsS2CMsg)(nil), "usercmd.CreateItemsS2CMsg")
	proto.RegisterType((*DestroyItemsS2CMsg)(nil), "usercmd.DestroyItemsS2CMsg")
	proto.RegisterEnum("usercmd.DemoTypeCmd", DemoTypeCmd_name, DemoTypeCmd_value)
	proto.RegisterEnum("usercmd.ColorType", ColorType_name, ColorType_value)
	proto.RegisterEnum("usercmd.ItemType", ItemType_name, ItemType_value)
}
func (m *MoveC2SMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MoveC2SMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.PlayerId))
	dAtA[i] = 0x15
	i++
	i = encodeFixed32MyDemo(dAtA, i, uint32(math.Float32bits(float32(m.PosX))))
	dAtA[i] = 0x1d
	i++
	i = encodeFixed32MyDemo(dAtA, i, uint32(math.Float32bits(float32(m.PosY))))
	dAtA[i] = 0x25
	i++
	i = encodeFixed32MyDemo(dAtA, i, uint32(math.Float32bits(float32(m.PosZ))))
	return i, nil
}

func (m *MoveS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MoveS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.PlayerId))
	dAtA[i] = 0x15
	i++
	i = encodeFixed32MyDemo(dAtA, i, uint32(math.Float32bits(float32(m.PosX))))
	dAtA[i] = 0x1d
	i++
	i = encodeFixed32MyDemo(dAtA, i, uint32(math.Float32bits(float32(m.PosY))))
	dAtA[i] = 0x25
	i++
	i = encodeFixed32MyDemo(dAtA, i, uint32(math.Float32bits(float32(m.PosZ))))
	return i, nil
}

func (m *LoginC2SMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginC2SMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(len(m.Name)))
	i += copy(dAtA[i:], m.Name)
	return i, nil
}

func (m *LoginS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.PlayerId))
	return i, nil
}

func (m *SearchC2SMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchC2SMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.PlayerId))
	return i, nil
}

func (m *SearchS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.RoomId))
	if len(m.Nums) > 0 {
		for _, msg := range m.Nums {
			dAtA[i] = 0x12
			i++
			i = encodeVarintMyDemo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SearchS2CMsgPlayer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchS2CMsgPlayer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.PlayerId))
	dAtA[i] = 0x12
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(len(m.Name)))
	i += copy(dAtA[i:], m.Name)
	return i, nil
}

func (m *GameStartS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameStartS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Nums) > 0 {
		for _, msg := range m.Nums {
			dAtA[i] = 0xa
			i++
			i = encodeVarintMyDemo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Edgenum))
	return i, nil
}

func (m *GameStartS2CMsgPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameStartS2CMsgPosition) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.PlayerId))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Row))
	dAtA[i] = 0x18
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Col))
	dAtA[i] = 0x20
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Color))
	return i, nil
}

func (m *ChangeColorS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChangeColorS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Color))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Row))
	dAtA[i] = 0x18
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Col))
	return i, nil
}

func (m *GameEndS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameEndS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Color))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Num))
	return i, nil
}

func (m *GameEnergyS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameEnergyS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Color))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Status))
	return i, nil
}

func (m *SynTimeS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SynTimeS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Tloop))
	return i, nil
}

func (m *CreateItemsS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateItemsS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Row))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Col))
	dAtA[i] = 0x18
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Item))
	return i, nil
}

func (m *DestroyItemsS2CMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DestroyItemsS2CMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Row))
	dAtA[i] = 0x10
	i++
	i = encodeVarintMyDemo(dAtA, i, uint64(m.Col))
	return i, nil
}

func encodeFixed64MyDemo(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32MyDemo(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMyDemo(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *MoveC2SMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.PlayerId))
	n += 5
	n += 5
	n += 5
	return n
}

func (m *MoveS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.PlayerId))
	n += 5
	n += 5
	n += 5
	return n
}

func (m *LoginC2SMsg) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	n += 1 + l + sovMyDemo(uint64(l))
	return n
}

func (m *LoginS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.PlayerId))
	return n
}

func (m *SearchC2SMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.PlayerId))
	return n
}

func (m *SearchS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.RoomId))
	if len(m.Nums) > 0 {
		for _, e := range m.Nums {
			l = e.Size()
			n += 1 + l + sovMyDemo(uint64(l))
		}
	}
	return n
}

func (m *SearchS2CMsgPlayer) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.PlayerId))
	l = len(m.Name)
	n += 1 + l + sovMyDemo(uint64(l))
	return n
}

func (m *GameStartS2CMsg) Size() (n int) {
	var l int
	_ = l
	if len(m.Nums) > 0 {
		for _, e := range m.Nums {
			l = e.Size()
			n += 1 + l + sovMyDemo(uint64(l))
		}
	}
	n += 1 + sovMyDemo(uint64(m.Edgenum))
	return n
}

func (m *GameStartS2CMsgPosition) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.PlayerId))
	n += 1 + sovMyDemo(uint64(m.Row))
	n += 1 + sovMyDemo(uint64(m.Col))
	n += 1 + sovMyDemo(uint64(m.Color))
	return n
}

func (m *ChangeColorS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.Color))
	n += 1 + sovMyDemo(uint64(m.Row))
	n += 1 + sovMyDemo(uint64(m.Col))
	return n
}

func (m *GameEndS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.Color))
	n += 1 + sovMyDemo(uint64(m.Num))
	return n
}

func (m *GameEnergyS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.Color))
	n += 1 + sovMyDemo(uint64(m.Status))
	return n
}

func (m *SynTimeS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.Tloop))
	return n
}

func (m *CreateItemsS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.Row))
	n += 1 + sovMyDemo(uint64(m.Col))
	n += 1 + sovMyDemo(uint64(m.Item))
	return n
}

func (m *DestroyItemsS2CMsg) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMyDemo(uint64(m.Row))
	n += 1 + sovMyDemo(uint64(m.Col))
	return n
}

func sovMyDemo(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMyDemo(x uint64) (n int) {
	return sovMyDemo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MoveC2SMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MoveC2SMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MoveC2SMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosX", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PosX = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosY", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PosY = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosZ", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PosZ = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("playerId")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("posX")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("posY")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("posZ")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MoveS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MoveS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MoveS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosX", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PosX = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosY", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PosY = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PosZ", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PosZ = float32(math.Float32frombits(v))
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("playerId")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("posX")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("posY")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("posZ")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginC2SMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginC2SMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginC2SMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMyDemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("name")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("playerId")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SearchC2SMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchC2SMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchC2SMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("playerId")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SearchS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomId", wireType)
			}
			m.RoomId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoomId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nums", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMyDemo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nums = append(m.Nums, &SearchS2CMsgPlayer{})
			if err := m.Nums[len(m.Nums)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("roomId")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SearchS2CMsgPlayer) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: player: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: player: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMyDemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("playerId")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("name")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameStartS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameStartS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameStartS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nums", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMyDemo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nums = append(m.Nums, &GameStartS2CMsgPosition{})
			if err := m.Nums[len(m.Nums)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Edgenum", wireType)
			}
			m.Edgenum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Edgenum |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("edgenum")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameStartS2CMsgPosition) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Row", wireType)
			}
			m.Row = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Row |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Col", wireType)
			}
			m.Col = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Col |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
			}
			m.Color = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Color |= (ColorType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("playerId")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("row")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("col")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("color")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChangeColorS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChangeColorS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChangeColorS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
			}
			m.Color = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Color |= (ColorType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Row", wireType)
			}
			m.Row = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Row |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Col", wireType)
			}
			m.Col = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Col |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("color")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("row")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("col")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameEndS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameEndS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameEndS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
			}
			m.Color = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Color |= (ColorType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("color")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("num")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameEnergyS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameEnergyS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameEnergyS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
			}
			m.Color = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Color |= (ColorType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("color")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("status")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SynTimeS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SynTimeS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SynTimeS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tloop", wireType)
			}
			m.Tloop = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tloop |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("tloop")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateItemsS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateItemsS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateItemsS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Row", wireType)
			}
			m.Row = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Row |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Col", wireType)
			}
			m.Col = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Col |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Item", wireType)
			}
			m.Item = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Item |= (ItemType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("row")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("col")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("item")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DestroyItemsS2CMsg) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DestroyItemsS2CMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DestroyItemsS2CMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Row", wireType)
			}
			m.Row = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Row |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Col", wireType)
			}
			m.Col = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Col |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMyDemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMyDemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("row")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("col")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMyDemo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMyDemo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMyDemo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMyDemo
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMyDemo
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMyDemo(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMyDemo = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMyDemo   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("MyDemo.proto", fileDescriptorMyDemo) }

var fileDescriptorMyDemo = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xed, 0x38, 0xce, 0xeb, 0xe6, 0xd1, 0xe9, 0x2c, 0x90, 0x55, 0x55, 0x21, 0x78, 0x43, 0xd5,
	0x4a, 0xa6, 0x8a, 0x04, 0x1f, 0xd0, 0x04, 0xa1, 0x4a, 0x74, 0xd3, 0x54, 0x82, 0x76, 0x85, 0x89,
	0x47, 0xae, 0x85, 0xed, 0x31, 0x33, 0x76, 0x2b, 0x4b, 0x7c, 0x02, 0x0b, 0x3e, 0x82, 0x8f, 0xe9,
	0xb2, 0x5f, 0x80, 0x50, 0xf9, 0x08, 0xb6, 0xe8, 0xda, 0x63, 0x37, 0x0d, 0x42, 0x0a, 0x65, 0xc1,
	0xf2, 0x9e, 0xfb, 0x38, 0x67, 0xce, 0x9d, 0x19, 0xe8, 0x1f, 0xe7, 0x33, 0x1e, 0x09, 0x27, 0x91,
	0x22, 0x15, 0xac, 0x9d, 0x29, 0x2e, 0x17, 0x91, 0x67, 0x7f, 0x02, 0x38, 0x16, 0x97, 0x7c, 0x3a,
	0x99, 0x1f, 0x2b, 0x9f, 0x8d, 0xa1, 0x93, 0x84, 0x6e, 0xce, 0xe5, 0x91, 0x67, 0x91, 0xb1, 0xb1,
	0x3b, 0x38, 0x34, 0xaf, 0xbf, 0x3d, 0xde, 0x38, 0xa9, 0x51, 0x66, 0x81, 0x99, 0x08, 0xf5, 0xd6,
	0x32, 0xc6, 0xc6, 0xae, 0xa1, 0xb3, 0x05, 0xa2, 0x33, 0x67, 0x56, 0x63, 0x25, 0x73, 0xa6, 0x33,
	0xe7, 0x96, 0xb9, 0x92, 0x39, 0xaf, 0xd8, 0xe7, 0x93, 0xe9, 0xff, 0x60, 0x7f, 0x0a, 0xbd, 0xd7,
	0xc2, 0x0f, 0x62, 0x7d, 0x78, 0x0b, 0xcc, 0xd8, 0x8d, 0x78, 0x41, 0xdd, 0xad, 0x0a, 0x11, 0xb1,
	0x9f, 0xe9, 0xc2, 0x75, 0x75, 0xda, 0x07, 0xd0, 0x9f, 0x73, 0x57, 0x2e, 0x2e, 0xd6, 0xf5, 0xd5,
	0xfe, 0x4a, 0xaa, 0x16, 0x4d, 0xb2, 0x03, 0x2d, 0x29, 0x44, 0xb4, 0xd2, 0xa0, 0x31, 0x76, 0x00,
	0x66, 0x9c, 0x45, 0xca, 0x32, 0xc6, 0x8d, 0xdd, 0xde, 0x64, 0xc7, 0xd1, 0xeb, 0x74, 0x96, 0x47,
	0x38, 0xe5, 0xf0, 0x93, 0xa2, 0x72, 0x7b, 0x06, 0xad, 0x32, 0x5e, 0xcf, 0xe6, 0xc2, 0x09, 0xe3,
	0x37, 0x27, 0x7e, 0x12, 0xd8, 0x7c, 0xe5, 0x46, 0x7c, 0x9e, 0xba, 0x32, 0xd5, 0x4a, 0x9f, 0x6b,
	0x2d, 0xa4, 0xd0, 0xf2, 0xa4, 0xd6, 0xb2, 0x52, 0xe7, 0x24, 0x42, 0x05, 0x69, 0x20, 0xe2, 0x52,
	0x10, 0x1b, 0x41, 0x9b, 0x7b, 0x3e, 0x8f, 0xb3, 0xa8, 0xe0, 0xa9, 0x54, 0x54, 0xe0, 0xf6, 0x67,
	0x02, 0x9d, 0xaa, 0x65, 0x0d, 0xcd, 0x8f, 0xa0, 0x21, 0xc5, 0xd5, 0xbd, 0x51, 0x08, 0x20, 0xbe,
	0x10, 0x61, 0x71, 0x2f, 0x6a, 0x7c, 0x21, 0x42, 0xe6, 0x40, 0x73, 0x21, 0x42, 0x21, 0x8b, 0x7b,
	0x31, 0x9c, 0xb0, 0x5a, 0x76, 0x81, 0x9e, 0xe6, 0x09, 0xd7, 0xd5, 0x65, 0x99, 0xad, 0x60, 0x6b,
	0x7a, 0xe1, 0xc6, 0x3e, 0x9f, 0x62, 0xa8, 0x8f, 0x5e, 0x0f, 0x21, 0x6b, 0x0d, 0xf9, 0x5b, 0x91,
	0xf6, 0x1b, 0x18, 0xa0, 0x8b, 0x2f, 0x63, 0xef, 0xe1, 0x84, 0xab, 0x06, 0x23, 0x60, 0xbf, 0x03,
	0x5a, 0x0e, 0xe6, 0xd2, 0xcf, 0x1f, 0x38, 0x7b, 0x07, 0x5a, 0x2a, 0x75, 0xd3, 0x4c, 0xdd, 0x1b,
	0xaf, 0x31, 0x7b, 0x1f, 0x06, 0xf3, 0x3c, 0x3e, 0x0d, 0xa2, 0xea, 0x75, 0x6f, 0x43, 0x33, 0x0d,
	0x85, 0x48, 0xee, 0xed, 0xaf, 0x84, 0xec, 0x04, 0xb6, 0xa6, 0x92, 0xbb, 0x29, 0x3f, 0x4a, 0x79,
	0xa4, 0x74, 0x83, 0x36, 0x8b, 0xfc, 0xc1, 0x2c, 0x63, 0x75, 0xa3, 0xfb, 0x60, 0x06, 0x29, 0x8f,
	0x0a, 0x17, 0x87, 0x93, 0xad, 0x5a, 0x3e, 0x82, 0x4b, 0xea, 0x8b, 0x22, 0x7b, 0x06, 0x6c, 0xc6,
	0x55, 0x2a, 0x45, 0xfe, 0x0f, 0x94, 0x7b, 0x37, 0x04, 0x7a, 0xf8, 0xab, 0xe2, 0xf8, 0x69, 0xe4,
	0xb1, 0x1e, 0xb4, 0xf1, 0x3f, 0x3b, 0xe1, 0x1f, 0x29, 0xb9, 0x0b, 0x14, 0x35, 0x58, 0x1f, 0x3a,
	0xc5, 0x17, 0x82, 0xa9, 0xc6, 0x52, 0xa4, 0xa8, 0xc9, 0x06, 0xd0, 0x2d, 0xdf, 0x2d, 0x26, 0x9b,
	0xcb, 0xa1, 0xa2, 0x2d, 0x0c, 0xeb, 0x97, 0x44, 0xdb, 0x8c, 0xc1, 0x70, 0xe9, 0x1e, 0x62, 0x49,
	0x17, 0x99, 0xf4, 0x35, 0xa1, 0xc0, 0x86, 0x00, 0x77, 0xab, 0xa5, 0x3d, 0xe4, 0xc2, 0x18, 0x37,
	0x41, 0xfb, 0x98, 0xc5, 0x03, 0x97, 0x6e, 0xd3, 0x01, 0xdb, 0x84, 0x1e, 0xc6, 0xda, 0x0b, 0x3a,
	0xdc, 0x7b, 0x01, 0xdd, 0x7a, 0xdf, 0x0c, 0xa0, 0x25, 0x64, 0xe0, 0x07, 0x31, 0xdd, 0x60, 0x6d,
	0x68, 0x48, 0xee, 0x51, 0x82, 0x60, 0xce, 0xc3, 0x50, 0x5c, 0x51, 0x83, 0x75, 0xc0, 0x7c, 0x1f,
	0x66, 0x9c, 0x36, 0xf6, 0x1c, 0xe8, 0x54, 0x46, 0xa3, 0x9e, 0x2c, 0xfe, 0x10, 0x8b, 0x2b, 0xec,
	0xeb, 0x42, 0xf3, 0x32, 0x90, 0x99, 0x2a, 0x3b, 0xbd, 0x9c, 0x07, 0xb1, 0x4f, 0x8d, 0x43, 0x7a,
	0x7d, 0x3b, 0x22, 0x37, 0xb7, 0x23, 0xf2, 0xfd, 0x76, 0x44, 0xbe, 0xfc, 0x18, 0x6d, 0xfc, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0xbd, 0x59, 0x26, 0xa2, 0x06, 0x00, 0x00,
}
